# version isn't needed as of 2020 for docker compose CLI. 
# All 2.x and 3.x features supported
version: '3.9'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - stack.env

  mysql:
    # we sue mariadb here for arm support
    # mariadb is a fork of MySQL that's often faster and better multi-platform
    image: mysql:5.6
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - stack.env

volumes:
  mysql-data:
  wordpress-data:
